<a href="https://colab.research.google.com/github/jongwoo1126/Colab/blob/master/Ch01.%20%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%20%EA%B8%B0%EC%B4%88.Numpy_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""
날짜 : 2022/04/28
이름 : 박종우
내용 : numpy 연습문제1
"""
import numpy as np

In [2]:
#01 파이썬 리스트 연산
list1 = [1, 2]
list2 = [3, 4]
print(list1 + list2)

[1, 2, 3, 4]


In [3]:
#02 넘파이 리스트(벡터) 연산
list1 = np.array([1,2])
list2 = np.array([3,4])
print(list1 + list2)

[4 6]


In [4]:
#03 0 벡터 생성 #1
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#04 0 벡터  생성 #2
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#05 10~49까지 벡터 생성
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#06 0부터 50까지 벡터 생성
z = np.arange(50)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [10]:
#07 index 1부터 index 10까지
z = np.arange(50)
z = z[1:10]
print(z)

[1 2 3 4 5 6 7 8 9]


In [12]:
#08 index 1부터 index 10까지 2칸 간격으로
z = np.arange(50)
z = z[1:10:2]
print(z)

[1 3 5 7 9]


In [13]:
#09 처음부터 끝까지 2칸 간격으로
z = np.arange(50)
z = z[::2]
print(z)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [15]:
#10 10부터 끝까지
z = np.arange(50)
z = z[10::]
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
#11 1부터 끝까지 2칸 간격으로
z = np.arange(50)
z = z[1::2]
print(z)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [17]:
#12 처음부터 끄까지 -1칸 간격으로(==역순으로)
z = np.arange(50)
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [20]:
#13 3X3 벡터(행렬) 생성
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
#14 3X3 벡터(행렬) 인덱싱
z = np.arange(9).reshape(3,3)
z = z[1:3, 0:3]
print(z)

[[3 4 5]
 [6 7 8]]


In [27]:
#15 3X3 벡터(행렬) 인덱싱
z = np.arange(9).reshape(3,3)
z = z[:2, 1:]
print(z)

[[1 2]
 [4 5]]


In [28]:
#16 3X3 벡터(행렬) 인덱싱
z = np.arange(9).reshape(3,3)
z = z[[0,1], 2]
print(z)

[2 5]


In [29]:
#17 3X3 벡터(행렬) 인덱싱
z = np.arange(9).reshape(3,3)
z = z[[0,1], 0:2]
print(z)

[[0 1]
 [3 4]]


In [30]:
#18 3X3 벡터(행렬) 인덱싱
z = np.arange(9).reshape(3,3)
z = z[[0,1]]
print(z)

[[0 1 2]
 [3 4 5]]


In [31]:
#19 2X3 벡터(행렬) 생성
z = np.arange(6).reshape(2,3)
print(z)

[[0 1 2]
 [3 4 5]]


In [32]:
#20 2X5 벡터(행렬) 생성
z = np.arange(10).reshape(2,5)
print(z)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [33]:
#21 5X2 벡터(행렬) 생성
z = np.arange(10).reshape(5,2)
print(z)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [38]:
#22 자동x5 벡터(행렬) 생성
z = np.arange(10).reshape(-1,5)
print(z)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [39]:
#23 5x자동 벡터(행렬) 생성
z = np.arange(10).reshape(5,-1)
print(z)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [40]:
#24 0이 아닌 값들의 index 반환
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [41]:
#25 2차 단위행렬
z = np.eye(2)
print(z)

[[1. 0.]
 [0. 1.]]


In [42]:
#26 3차 단위행렬
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
#27 3x3x3벡터 생성
z = np.random.random((3,3,3))
print(z)

[[[0.82164065 0.74763438 0.05134488]
  [0.5785497  0.01946997 0.94870787]
  [0.53165369 0.18047704 0.35213592]]

 [[0.30021754 0.17821918 0.77893237]
  [0.863931   0.21612204 0.54795588]
  [0.72357308 0.98189376 0.97742777]]

 [[0.12140311 0.88974842 0.87131527]
  [0.77601947 0.63479984 0.49942909]
  [0.18251614 0.33457517 0.98813211]]]


In [46]:
#28 10x10 벡터에서 최대, 최솟값
z = np.random.random((10,10))
z_min, z_max = z.min(), z.max()
print(z_min,z_max)

0.023098327851765466 0.9971007417160661


In [47]:
#29 벡터 평균
z = np.random.random(30)
m = z.mean()
print(m)

0.4476928871801829


In [48]:
#30 10x10 벡터에서 border가 1인 벡터
z = np.ones((10, 10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [50]:
#31 10x10 벡터에서 0,1 체크무늬 벡터
z = np.zeros((10,10))
z[1::2,::2] = 1
z[::2, 1::2] = 1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]
