<a href="https://colab.research.google.com/github/jongwoo1126/Colab/blob/master/Ch03.%20%EB%94%A5%EB%9F%AC%EB%8B%9D%20%EC%8B%A4%EC%8A%B5/4_%EB%94%A5%EB%9F%AC%EB%8B%9D_CNN_%EB%AA%A8%EB%8D%B8_%ED%85%8C%EC%8A%A4%ED%8A%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2022/05/10
이름 : 박종우
내용 : 딥러닝 CNN 모델 테스트 실습
"""
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets.cifar10 import load_data
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from sklearn.model_selection import train_test_split
from PIL import Image
tf.__version__

'2.8.0'

In [ ]:
# 데이터 불러오기
(cifar_train_data, cifar_train_label), (cifar_test_data, cifar_test_label) = load_data()

In [ ]:
# 모델 학습을 위한 데이터 전처리(정규화)
cifar_train_data2 = cifar_train_data / 255
cifar_test_data2 = cifar_test_data / 255

In [ ]:
# 데이터 라벨을 범주형(one-hot encoding)으로 변환
cifar_train_label2 = to_categorical(cifar_train_label)
cifar_test_label2 = to_categorical(cifar_test_label)
cifar_train_label2[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [ ]:
# 외부학습모델 불러오기
model = load_model('//content/drive/MyDrive/파이썬 데이터 과학 실습/file/cifar_model.h5')

In [ ]:
# 모델 테스트
result = model.evaluate(cifar_test_data2, cifar_test_label2)
result

313/313 [==============================] - 21s 67ms/step - loss: 1.0946 - acc: 0.7642


[1.0946159362792969, 0.76419997215271]

In [ ]:
##############################################################################################
# 이미지 로드 함수 정의
def load_image(filename):
	# load the image
	img = load_img(filename, target_size=(32, 32))
	# convert to array
	img = img_to_array(img)
	# reshape into a single sample with 3 channels
	img = img.reshape(1, 32, 32, 3)
	# prepare pixel data
	img = img.astype('float32')
	img = img / 255.0
	return img

In [ ]:
img = load_image('/content/drive/MyDrive/파이썬 데이터 과학 실습/file/frog.jpg')
img

array([[[[0.3647059 , 0.46666667, 0.21960784],
         [0.3019608 , 0.4117647 , 0.10980392],
         [0.3019608 , 0.43137255, 0.07450981],
         ...,
         [0.39215687, 0.5058824 , 0.19215687],
         [0.32941177, 0.4392157 , 0.14901961],
         [0.28627452, 0.39607844, 0.10588235]],

        [[0.3882353 , 0.49019608, 0.23529412],
         [0.36862746, 0.48235294, 0.16862746],
         [0.33333334, 0.4627451 , 0.11372549],
         ...,
         [0.3372549 , 0.4392157 , 0.15294118],
         [0.31764707, 0.41960785, 0.13333334],
         [0.30980393, 0.40392157, 0.09803922]],

        [[0.3764706 , 0.47843137, 0.22352941],
         [0.3647059 , 0.47843137, 0.16470589],
         [0.30980393, 0.42352942, 0.09411765],
         ...,
         [0.31764707, 0.40392157, 0.16078432],
         [0.31764707, 0.4       , 0.13725491],
         [0.3254902 , 0.4117647 , 0.09019608]],

        ...,

        [[0.37254903, 0.45490196, 0.19215687],
         [0.36862746, 0.41960785, 0.21176471]

In [ ]:
# 이미지 모델 테스트
result = model.predict(img)
result.round()

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)